[package]
name = "c4solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.19"
enum-utils = "0.1.2"
timens = "0.1.4"
